"""create V1 industrial data schema

Revision ID: 0e66bfb68f1d
Revises:
Create Date: 2026-08-19 03:14:03.407049

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e66bfb68f1d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=100), nullable=False),
        sa.Column("user_query", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "waiting_for_approval",
                "completed",
                "failed",
                "abstained",
                name="agent_run_status_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_provider", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("model_calls", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("final_response", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=150), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'waiting_for_approval') OR completed_at IS NOT NULL",
            name="ck_agent_runs_completion_timestamp",
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0", name="ck_agent_runs_duration_nonnegative"
        ),
        sa.CheckConstraint("estimated_cost_usd >= 0", name="ck_agent_runs_cost_nonnegative"),
        sa.CheckConstraint("model_calls >= 0", name="ck_agent_runs_model_calls_nonnegative"),
        sa.CheckConstraint(
            "prompt_tokens >= 0 AND completion_tokens >= 0 AND total_tokens >= 0",
            name="ck_agent_runs_tokens_nonnegative",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum(
                "pump", "motor", name="asset_type_enum", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "operational",
                "standby",
                "maintenance",
                "out_of_service",
                name="asset_status_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "criticality",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="criticality_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=150), nullable=False),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model_number", sa.String(length=100), nullable=True),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_asset_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_asset_code"), ["asset_code"], unique=True)

    op.create_table(
        "agent_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "routing",
                "tool_selection",
                "tool_execution",
                "evidence_synthesis",
                "guardrail",
                "approval_pause",
                "final_response",
                name="agent_step_type_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                "skipped",
                name="agent_step_status_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=150), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status = 'running' OR completed_at IS NOT NULL",
            name="ck_agent_steps_completion_timestamp",
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0", name="ck_agent_steps_duration_nonnegative"
        ),
        sa.CheckConstraint("step_number > 0", name="ck_agent_steps_step_number_positive"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "step_number", name="uq_agent_steps_run_step_number"),
    )
    op.create_table(
        "maintenance_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "maintenance_type",
            sa.Enum(
                "preventive",
                "corrective",
                "predictive",
                "inspection",
                name="maintenance_type_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=255), nullable=False),
        sa.Column("findings", sa.Text(), nullable=False),
        sa.Column("action_taken", sa.Text(), nullable=False),
        sa.Column("technician", sa.String(length=100), nullable=False),
        sa.Column("downtime_hours", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "downtime_hours >= 0", name="ck_maintenance_records_downtime_nonnegative"
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("maintenance_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_maintenance_records_asset_performed_at", ["asset_id", "performed_at"], unique=False
        )

    op.create_table(
        "sensor_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "sensor_type",
            sa.Enum(
                "vibration",
                "temperature",
                "suction_pressure",
                "discharge_pressure",
                "flow_rate",
                "motor_current",
                name="sensor_type_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column(
            "quality",
            sa.Enum(
                "good",
                "suspect",
                "bad",
                name="data_quality_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "asset_id", "recorded_at", "sensor_type", name="uq_sensor_reading_asset_time_type"
        ),
    )
    with op.batch_alter_table("sensor_readings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sensor_readings_asset_recorded_at", ["asset_id", "recorded_at"], unique=False
        )

    op.create_table(
        "work_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_order_number", sa.String(length=30), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="work_order_priority_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "pending_approval",
                "approved",
                "rejected",
                "executed",
                "cancelled",
                name="work_order_status_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("proposed_by", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status != 'executed' OR executed_at IS NOT NULL",
            name="ck_work_orders_execution_timestamp",
        ),
        sa.CheckConstraint("revision > 0", name="ck_work_orders_revision_positive"),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("work_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_work_orders_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_work_orders_work_order_number"), ["work_order_number"], unique=True
        )

    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_order_id", sa.Integer(), nullable=False),
        sa.Column("request_version", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "expired",
                "revoked",
                name="approval_decision_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("approval_scope", sa.String(length=100), nullable=False),
        sa.Column("requested_by", sa.String(length=100), nullable=False),
        sa.Column("decided_by", sa.String(length=100), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            (
                "(decision = 'pending' AND decided_at IS NULL "
                "AND decided_by IS NULL) OR "
                "(decision != 'pending' AND decided_at IS NOT NULL "
                "AND decided_by IS NOT NULL)"
            ),
            name="ck_approvals_decision_metadata",
        ),
        sa.CheckConstraint("request_version > 0", name="ck_approvals_request_version_positive"),
        sa.ForeignKeyConstraint(["work_order_id"], ["work_orders.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "work_order_id", "request_version", name="uq_approvals_work_order_version"
        ),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=True),
        sa.Column("approval_id", sa.Integer(), nullable=True),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("arguments_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "succeeded",
                "failed",
                "blocked",
                name="tool_call_status_enum",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_state_changing", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=150), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status = 'requested' OR completed_at IS NOT NULL",
            name="ck_tool_calls_completion_timestamp",
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0", name="ck_tool_calls_latency_nonnegative"
        ),
        sa.ForeignKeyConstraint(["approval_id"], ["approvals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["agent_steps.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool_calls")
    op.drop_table("approvals")
    with op.batch_alter_table("work_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_work_orders_work_order_number"))
        batch_op.drop_index(batch_op.f("ix_work_orders_idempotency_key"))

    op.drop_table("work_orders")
    with op.batch_alter_table("sensor_readings", schema=None) as batch_op:
        batch_op.drop_index("ix_sensor_readings_asset_recorded_at")

    op.drop_table("sensor_readings")
    with op.batch_alter_table("maintenance_records", schema=None) as batch_op:
        batch_op.drop_index("ix_maintenance_records_asset_performed_at")

    op.drop_table("maintenance_records")
    op.drop_table("agent_steps")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_asset_code"))

    op.drop_table("assets")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_thread_id"))

    op.drop_table("agent_runs")
    # ### end Alembic commands ###
